name = "taffy-default"
mc_version = "1.21.4"

[jar]
type = "paper"

[variables]
SERVER_PORT = "25565"

[launcher]
eula_args = true
nogui = true

[markdown]
files = ["README.md"]
auto_update = true

[options]
success_line = ""
stop_command = ""
